image: microsoft/dotnet:2.1-sdk

options:
    docker: true

pipelines:
    default:
    - step:
          caches:
          - docker
          - dotnetcore
          script:
          - apt-get install -y --no-install-recommends mono
          - ./build.sh
