image: microsoft/dotnet:2.1-sdk

options:
    docker: true

pipelines:
    default:
    - step:
          caches:
          - docker
          - dotnetcore
          script:
          - apt update
          - apt install -y --no-install-recommends apt-transport-https dirmngr
          - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          - echo "deb https://download.mono-project.com/repo/debian stable-stretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          - apt update
          - apt install -y --no-install-recommends mono-devel
          - ./build.sh
